# print("hello world")
# print("that's my first python code")
# print("my name is gunjan asodariya")
# name="gunjan"
# age="18"
# city="gujrat"
# print(name, age, city)ghgh
bddrtherbfgrthdyrthetgsrgdbfddvsvdxfsfbehetrdfthgrefergzcsetrhthethrrgedfbdferrrwrgethdnethsvdssbgrwrsdgsgfdfeye45yherththgefvfhwrthwrtrhvvvgncehethrferrvfwesgrthrggthhrhdrthhhhrtrttrhcsdfbsrthehtwrsfhdbffbdxbehdvjehgehtdfhfwhwredtjfgfngnehtdngbvthdthgtdhfvbdfbxsbdbfb bdfbdhcvbffvsdfdbcffvsdfv xvbxfbddfsdfgdfgfdsgdhdghdthhfxhtdfbrfdcv hbdfddvwdvctbvfdfvcfvheffterfdfgbgtregrfsvfdfdv35terftgvnbnnxgngdbffdgfbfgbfhjmjmjmvnfghnfdbfdgbdfgbdfgbdfgbdfgbdfgbdfgbdfgbgunjan asodariya dfvsdffdsvfs