# print("hello world")
# print("that's my first python code")
# print("my name is gunjan asodariya")
# name="gunjan"
# age="18"vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
# city="gujrat"
# print(name, age, city)ghghdsfgsdfgvvvvvvvvvvvsdfgsdfgsdfgsdfgsdfgdfgvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
bddrtherbfgrthdyrthetgsrgdbfddvsvdxfsfbehetrdfthgrefergzcsetrhthethrrgedfbdferrrwrgethdnethsvdssbgrwrsdgsgfvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvfeye45yherththgefvfhwrfdgrtyurtyur4turhcsdfbsrdfghdfghthehtwrsfhdbffbdxbehdvfgsdfgsdfgsdfgsdfgsdfgsdfgsdfgdfgsdfgsdfgsdfgsdfgsdfgsdfgsdfgsdfgxvbxfbddfsdfgdfgfdsgdhdghddfgdcfghcfghxhtdfbrdfvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvsdfdcv 4w56w456w456rt5yertyytrtrtyhrttydfgdfgdfgdfg56w456454536356sdfgsdfsdffffffffffffffffgsdfgsdgvvvvvvvvvvvvvvvvvfgsdfgsdfgvvvvvvvvvvvvvvvvvvvvvvvvvvvvvrtyertyetyyvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvhbdfddvwdvctbvfdfvcfvdsfvfvsdsdfsvvvvvvvvtyretyevvvvvvvvvvvvvvvvvvdfhesdsdfgsdfgfgsdfgffterfdfgbgtregrfsvfdfdv35terftgvnbnnxgngdbffdvvvvvvvvvvvvvvvvvvvvgfbfgbfhjmjmjmvnfghnfdbfdgbdfgbdfgbdfgbdfgsdfgsdfgbdfgbdfgbdfgbgunjan asodariya dfvsdffdsvfsfsdsfvsdfgfdfvsuir7r67dfg edrghsuys d