# print("hello world")
# print("that's my first python code")
# print("my name is gunjan asodariya")
# name="gunjan"
# age="18"
# city="gujrat"
# print(name, age, city)ghghdsfgsdfgvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
bddrtherbfgrthdyrthetgsrgdbfddvsvdxfsfbehetrdfthgrefergzcsetrhthethrrgedfbdferrrwrgethdnethsvdssbgrwrsdgsgfdfeye45yherththgefvfhwrfdgsdfgsfdgdsfthwrtrhvvvgncehethrferrvfwesgrthrggthhrhdrthhhhrtrttrhcsdfbsrthehtwrsfhdbffbdxbehdvjehgehtdfhfwhwredtjfgfngnehtdngbvthdthgtdhfvbdfbxsbdbfb bdfbdhcvbffvsdfdbcffvsdfv sdfgsdfgxvbxfbddfsdfgdfgfdsgdhdghddfgdfgthhfxhtdfbrdfsdfdcv hbdfddvwdvctbvfdfvcfvdsfvfvsdsdfsdfhesdsdfgsdfgfgsdfgffterfdfgbgtregrfsvfdfdv35terftgvnbnnxgngdbffdvvvvvvvvvvvvvvvvvvvvgfbfgbfhjmjmjmvnfghnfdbfdgbdfgbdfgbdfgbdfgsdfgsdfgbdfgbdfgbdfgbgunjan asodariya dfvsdffdsvfsfsdsfvsdfgfdfvsdfg